// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pubkyFFI)
import pubkyFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pubky_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pubky_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePubkyInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol FfiKeyProvider: AnyObject, Sendable {
    
    func secretKey() throws  -> Data
    
}
open class FfiKeyProviderImpl: FfiKeyProvider, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_ffikeyprovider(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pubky_fn_free_ffikeyprovider(pointer, $0) }
    }

    

    
open func secretKey()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFfiPubkyError_lift) {
    uniffi_pubky_fn_method_ffikeyprovider_secret_key(self.uniffiClonePointer(),$0
    )
})
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiKeyProvider {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceFfiKeyProvider] = [UniffiVTableCallbackInterfaceFfiKeyProvider(
        secretKey: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterTypeFfiKeyProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.secretKey(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeFfiPubkyError_lower
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeFfiKeyProvider.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FfiKeyProvider: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitFfiKeyProvider() {
    uniffi_pubky_fn_init_callback_vtable_ffikeyprovider(UniffiCallbackInterfaceFfiKeyProvider.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiKeyProvider: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<FfiKeyProvider>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiKeyProvider

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiKeyProvider {
        return FfiKeyProviderImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiKeyProvider) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiKeyProvider {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiKeyProvider, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyProvider_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiKeyProvider {
    return try FfiConverterTypeFfiKeyProvider.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyProvider_lower(_ value: FfiKeyProvider) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiKeyProvider.lower(value)
}






public protocol FfiPubkySessionProtocol: AnyObject, Sendable {
    
    func info()  -> FfiSessionInfo
    
    func signout() async throws 
    
    func storage()  -> FfiSessionStorage
    
}
open class FfiPubkySession: FfiPubkySessionProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_ffipubkysession(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pubky_fn_free_ffipubkysession(pointer, $0) }
    }

    

    
open func info() -> FfiSessionInfo  {
    return try!  FfiConverterTypeFfiSessionInfo_lift(try! rustCall() {
    uniffi_pubky_fn_method_ffipubkysession_info(self.uniffiClonePointer(),$0
    )
})
}
    
open func signout()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffipubkysession_signout(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_void,
            completeFunc: ffi_pubky_rust_future_complete_void,
            freeFunc: ffi_pubky_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func storage() -> FfiSessionStorage  {
    return try!  FfiConverterTypeFfiSessionStorage_lift(try! rustCall() {
    uniffi_pubky_fn_method_ffipubkysession_storage(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPubkySession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiPubkySession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiPubkySession {
        return FfiPubkySession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiPubkySession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPubkySession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiPubkySession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPubkySession_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiPubkySession {
    return try FfiConverterTypeFfiPubkySession.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPubkySession_lower(_ value: FfiPubkySession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiPubkySession.lower(value)
}






public protocol FfiPublicStorageProtocol: AnyObject, Sendable {
    
    func get(uri: String) async throws  -> Data
    
    func list(uri: String) async throws  -> [FfiListItem]
    
}
open class FfiPublicStorage: FfiPublicStorageProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_ffipublicstorage(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pubky_fn_free_ffipublicstorage(pointer, $0) }
    }

    

    
open func get(uri: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffipublicstorage_get(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(uri)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_rust_buffer,
            completeFunc: ffi_pubky_rust_future_complete_rust_buffer,
            freeFunc: ffi_pubky_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func list(uri: String)async throws  -> [FfiListItem]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffipublicstorage_list(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(uri)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_rust_buffer,
            completeFunc: ffi_pubky_rust_future_complete_rust_buffer,
            freeFunc: ffi_pubky_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiListItem.lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPublicStorage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiPublicStorage

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiPublicStorage {
        return FfiPublicStorage(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiPublicStorage) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPublicStorage {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiPublicStorage, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPublicStorage_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiPublicStorage {
    return try FfiConverterTypeFfiPublicStorage.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPublicStorage_lower(_ value: FfiPublicStorage) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiPublicStorage.lower(value)
}






public protocol FfiSdkProtocol: AnyObject, Sendable {
    
    func awaitApproval(requestId: String) async throws  -> FfiPubkySession
    
    func publicStorage()  -> FfiPublicStorage
    
    func signin(keyProvider: FfiKeyProvider, homeserver: String) async throws  -> FfiPubkySession
    
    func signup(keyProvider: FfiKeyProvider, homeserver: String, options: FfiSignupOptions?) async throws  -> FfiPubkySession
    
    func startAuthFlow(capabilities: [String]) throws  -> FfiAuthFlowInfo
    
}
open class FfiSdk: FfiSdkProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_ffisdk(self.pointer, $0) }
    }
public convenience init()throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFfiPubkyError_lift) {
    uniffi_pubky_fn_constructor_ffisdk_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pubky_fn_free_ffisdk(pointer, $0) }
    }

    

    
open func awaitApproval(requestId: String)async throws  -> FfiPubkySession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisdk_await_approval(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(requestId)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_pointer,
            completeFunc: ffi_pubky_rust_future_complete_pointer,
            freeFunc: ffi_pubky_rust_future_free_pointer,
            liftFunc: FfiConverterTypeFfiPubkySession_lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func publicStorage() -> FfiPublicStorage  {
    return try!  FfiConverterTypeFfiPublicStorage_lift(try! rustCall() {
    uniffi_pubky_fn_method_ffisdk_public_storage(self.uniffiClonePointer(),$0
    )
})
}
    
open func signin(keyProvider: FfiKeyProvider, homeserver: String)async throws  -> FfiPubkySession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisdk_signin(
                    self.uniffiClonePointer(),
                    FfiConverterTypeFfiKeyProvider_lower(keyProvider),FfiConverterString.lower(homeserver)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_pointer,
            completeFunc: ffi_pubky_rust_future_complete_pointer,
            freeFunc: ffi_pubky_rust_future_free_pointer,
            liftFunc: FfiConverterTypeFfiPubkySession_lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func signup(keyProvider: FfiKeyProvider, homeserver: String, options: FfiSignupOptions?)async throws  -> FfiPubkySession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisdk_signup(
                    self.uniffiClonePointer(),
                    FfiConverterTypeFfiKeyProvider_lower(keyProvider),FfiConverterString.lower(homeserver),FfiConverterOptionTypeFfiSignupOptions.lower(options)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_pointer,
            completeFunc: ffi_pubky_rust_future_complete_pointer,
            freeFunc: ffi_pubky_rust_future_free_pointer,
            liftFunc: FfiConverterTypeFfiPubkySession_lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func startAuthFlow(capabilities: [String])throws  -> FfiAuthFlowInfo  {
    return try  FfiConverterTypeFfiAuthFlowInfo_lift(try rustCallWithError(FfiConverterTypeFfiPubkyError_lift) {
    uniffi_pubky_fn_method_ffisdk_start_auth_flow(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(capabilities),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSdk: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiSdk

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiSdk {
        return FfiSdk(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiSdk) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSdk {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiSdk, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSdk_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiSdk {
    return try FfiConverterTypeFfiSdk.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSdk_lower(_ value: FfiSdk) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiSdk.lower(value)
}






public protocol FfiSessionStorageProtocol: AnyObject, Sendable {
    
    func delete(path: String) async throws 
    
    func get(path: String) async throws  -> Data
    
    func list(path: String) async throws  -> [FfiListItem]
    
    func put(path: String, content: Data) async throws 
    
}
open class FfiSessionStorage: FfiSessionStorageProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_ffisessionstorage(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pubky_fn_free_ffisessionstorage(pointer, $0) }
    }

    

    
open func delete(path: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisessionstorage_delete(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_void,
            completeFunc: ffi_pubky_rust_future_complete_void,
            freeFunc: ffi_pubky_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func get(path: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisessionstorage_get(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_rust_buffer,
            completeFunc: ffi_pubky_rust_future_complete_rust_buffer,
            freeFunc: ffi_pubky_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func list(path: String)async throws  -> [FfiListItem]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisessionstorage_list(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_rust_buffer,
            completeFunc: ffi_pubky_rust_future_complete_rust_buffer,
            freeFunc: ffi_pubky_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiListItem.lift,
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    
open func put(path: String, content: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pubky_fn_method_ffisessionstorage_put(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(path),FfiConverterData.lower(content)
                )
            },
            pollFunc: ffi_pubky_rust_future_poll_void,
            completeFunc: ffi_pubky_rust_future_complete_void,
            freeFunc: ffi_pubky_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiPubkyError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSessionStorage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiSessionStorage

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiSessionStorage {
        return FfiSessionStorage(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiSessionStorage) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSessionStorage {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiSessionStorage, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionStorage_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiSessionStorage {
    return try FfiConverterTypeFfiSessionStorage.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionStorage_lower(_ value: FfiSessionStorage) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiSessionStorage.lower(value)
}




public struct FfiAuthFlowInfo {
    public var authorizationUrl: String
    public var requestId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(authorizationUrl: String, requestId: String) {
        self.authorizationUrl = authorizationUrl
        self.requestId = requestId
    }
}

#if compiler(>=6)
extension FfiAuthFlowInfo: Sendable {}
#endif


extension FfiAuthFlowInfo: Equatable, Hashable {
    public static func ==(lhs: FfiAuthFlowInfo, rhs: FfiAuthFlowInfo) -> Bool {
        if lhs.authorizationUrl != rhs.authorizationUrl {
            return false
        }
        if lhs.requestId != rhs.requestId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(authorizationUrl)
        hasher.combine(requestId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAuthFlowInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAuthFlowInfo {
        return
            try FfiAuthFlowInfo(
                authorizationUrl: FfiConverterString.read(from: &buf), 
                requestId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAuthFlowInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.authorizationUrl, into: &buf)
        FfiConverterString.write(value.requestId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAuthFlowInfo_lift(_ buf: RustBuffer) throws -> FfiAuthFlowInfo {
    return try FfiConverterTypeFfiAuthFlowInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAuthFlowInfo_lower(_ value: FfiAuthFlowInfo) -> RustBuffer {
    return FfiConverterTypeFfiAuthFlowInfo.lower(value)
}


public struct FfiListItem {
    public var name: String
    public var isDirectory: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, isDirectory: Bool) {
        self.name = name
        self.isDirectory = isDirectory
    }
}

#if compiler(>=6)
extension FfiListItem: Sendable {}
#endif


extension FfiListItem: Equatable, Hashable {
    public static func ==(lhs: FfiListItem, rhs: FfiListItem) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.isDirectory != rhs.isDirectory {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(isDirectory)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiListItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiListItem {
        return
            try FfiListItem(
                name: FfiConverterString.read(from: &buf), 
                isDirectory: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiListItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.isDirectory, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiListItem_lift(_ buf: RustBuffer) throws -> FfiListItem {
    return try FfiConverterTypeFfiListItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiListItem_lower(_ value: FfiListItem) -> RustBuffer {
    return FfiConverterTypeFfiListItem.lower(value)
}


public struct FfiSessionInfo {
    public var pubkey: String
    public var sessionSecret: String?
    public var capabilities: [String]
    public var createdAt: UInt64
    public var expiresAt: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, sessionSecret: String?, capabilities: [String], createdAt: UInt64, expiresAt: UInt64?) {
        self.pubkey = pubkey
        self.sessionSecret = sessionSecret
        self.capabilities = capabilities
        self.createdAt = createdAt
        self.expiresAt = expiresAt
    }
}

#if compiler(>=6)
extension FfiSessionInfo: Sendable {}
#endif


extension FfiSessionInfo: Equatable, Hashable {
    public static func ==(lhs: FfiSessionInfo, rhs: FfiSessionInfo) -> Bool {
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        if lhs.sessionSecret != rhs.sessionSecret {
            return false
        }
        if lhs.capabilities != rhs.capabilities {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.expiresAt != rhs.expiresAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkey)
        hasher.combine(sessionSecret)
        hasher.combine(capabilities)
        hasher.combine(createdAt)
        hasher.combine(expiresAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSessionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSessionInfo {
        return
            try FfiSessionInfo(
                pubkey: FfiConverterString.read(from: &buf), 
                sessionSecret: FfiConverterOptionString.read(from: &buf), 
                capabilities: FfiConverterSequenceString.read(from: &buf), 
                createdAt: FfiConverterUInt64.read(from: &buf), 
                expiresAt: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSessionInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterOptionString.write(value.sessionSecret, into: &buf)
        FfiConverterSequenceString.write(value.capabilities, into: &buf)
        FfiConverterUInt64.write(value.createdAt, into: &buf)
        FfiConverterOptionUInt64.write(value.expiresAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionInfo_lift(_ buf: RustBuffer) throws -> FfiSessionInfo {
    return try FfiConverterTypeFfiSessionInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionInfo_lower(_ value: FfiSessionInfo) -> RustBuffer {
    return FfiConverterTypeFfiSessionInfo.lower(value)
}


public struct FfiSignupOptions {
    public var capabilities: [String]?
    public var signupToken: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(capabilities: [String]?, signupToken: UInt64?) {
        self.capabilities = capabilities
        self.signupToken = signupToken
    }
}

#if compiler(>=6)
extension FfiSignupOptions: Sendable {}
#endif


extension FfiSignupOptions: Equatable, Hashable {
    public static func ==(lhs: FfiSignupOptions, rhs: FfiSignupOptions) -> Bool {
        if lhs.capabilities != rhs.capabilities {
            return false
        }
        if lhs.signupToken != rhs.signupToken {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(capabilities)
        hasher.combine(signupToken)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSignupOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSignupOptions {
        return
            try FfiSignupOptions(
                capabilities: FfiConverterOptionSequenceString.read(from: &buf), 
                signupToken: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSignupOptions, into buf: inout [UInt8]) {
        FfiConverterOptionSequenceString.write(value.capabilities, into: &buf)
        FfiConverterOptionUInt64.write(value.signupToken, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSignupOptions_lift(_ buf: RustBuffer) throws -> FfiSignupOptions {
    return try FfiConverterTypeFfiSignupOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSignupOptions_lower(_ value: FfiSignupOptions) -> RustBuffer {
    return FfiConverterTypeFfiSignupOptions.lower(value)
}


public enum FfiPubkyError: Swift.Error {

    
    
    case Auth(message: String)
    
    case Request(message: String)
    
    case Build(message: String)
    
    case InvalidInput(message: String)
    
    case Network(message: String)
    
    case Unknown(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPubkyError: FfiConverterRustBuffer {
    typealias SwiftType = FfiPubkyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPubkyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Auth(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Request(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Build(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Unknown(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPubkyError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Auth(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Request(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Build(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Unknown(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPubkyError_lift(_ buf: RustBuffer) throws -> FfiPubkyError {
    return try FfiConverterTypeFfiPubkyError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPubkyError_lower(_ value: FfiPubkyError) -> RustBuffer {
    return FfiConverterTypeFfiPubkyError.lower(value)
}


extension FfiPubkyError: Equatable, Hashable {}




extension FfiPubkyError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiSignupOptions: FfiConverterRustBuffer {
    typealias SwiftType = FfiSignupOptions?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiSignupOptions.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiSignupOptions.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiListItem: FfiConverterRustBuffer {
    typealias SwiftType = [FfiListItem]

    public static func write(_ value: [FfiListItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiListItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiListItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiListItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiListItem.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePubkyInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pubky_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pubky_checksum_method_ffikeyprovider_secret_key() != 37759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffipubkysession_info() != 29805) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffipubkysession_signout() != 23828) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffipubkysession_storage() != 10306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffipublicstorage_get() != 37518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffipublicstorage_list() != 5388) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisdk_await_approval() != 34312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisdk_public_storage() != 47373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisdk_signin() != 52011) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisdk_signup() != 42095) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisdk_start_auth_flow() != 35268) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisessionstorage_delete() != 29717) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisessionstorage_get() != 28268) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisessionstorage_list() != 44543) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_ffisessionstorage_put() != 32992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_constructor_ffisdk_new() != 22016) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFfiKeyProvider()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePubkyInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all